### PR TITLE
Added proper return path to preview screens via flash() scope

### PR DESCRIPTION
**Pull request by kostya-lnk-ms**

### CODE REVIEW

**Comment by DougC** [comment]
Hmm, would this be better as a (perhaps optional) query parameter on the url? We've used that in at least one other place, I think

**Comment by kostya-lnk-ms** [comment]
Doug,

I guess that depends on whether we want to allow a user to bookmark the preview page and being able to return to the editing section.
I'd rather not to pass URLs via URL unless we want bookmarking to work.
The flash() is for that purpose - to pass something one-off to a page, right?

**Comment by DougC** [comment]
Good arguments either way, I guess. But bookmarking is a big one. If they bookmark the page and come back later they'll get a different back link.

**Comment by kostya-lnk-ms** [comment]
However, if an opportunity is finalized, then that back link would become invalid.
I guess we should ask our BAs what to do.
I am happy to change to an URL parameter, if there we need to be strict on bookmarking.

**Comment by DougC** [comment]
Yeah, it's an awkward one. Leave it for now. Happy for you to merge it.

**Pull request merged**
