### PR TITLE
Feature/1162 preview costs

### PR DESCRIPTION
**Pull request by DougC**
Quite a bit of change here, mainly reflecting the change to the type signatures of the various methods involved with field rendering and previewing. I'll need to merge from master before this is ready to go.

### CODE REVIEW

**Comment by DougC** [comment]
Thanks for the layout changes @jon-shipley. I've fixed the total on the preview page so I think this is ready to go. What do you think?

**Comment by jon-shipley** [comment]
Looks good to me. 👍

**Comment by DougC** [comment]
you closed it - were you trying to merge? :-)

**Comment by jon-shipley** [comment]
Oh no!  I was just trying to add a comment.

**Comment by DougC** [comment]
In fact I think I'd like to hold off merging this until we've merged Ben's PR https://github.com/UKGovernmentBEIS/rifs-frontend-play/pull/60 as I think there will be merge conflicts

**Comment by DougC** [comment]
Okay, once the checks are done I think this ready to go. I've merged the changes from Ben's PR,

**Pull request merged**
